### PR TITLE
Swift 2.0 Conversion

### PR DESCRIPTION
**Pull request by mitchins**
Bare minimal to compile in swift 2.0 and remove and associated warnings
from var to let as per the new code analyzer.

Disregard if you've done this and decline it, but I needed this for myself and wanted the chance to see if it helps you.

### CODE REVIEW

**Comment by ortuman** [comment]
Thanks for sharing mitchins! Merging!

**Comment by kdomingo** [comment]
How do I update this for cocoa pods?

**Comment by mitchins** [comment]
You can add a new version in the pod spec file, and then tag or branch that version in GIT.









—

**Comment by ortuman** [comment]
Hi Mitchell

I’ve just uploaded the new version to the pods repository. Tell me if you have any other problem trying to integrate it. And thanks for the feedback. Appreciate it.

-- 
Miguel Ángel
Sent with Airmail

En 24 de septiembre de 2015 en 22:01:37, Mitchell Currie (notifications@github.com) escrito:

You can add a new version in the pod spec file, and then tag or branch that version in GIT.









—

**Pull request merged**
