### PR TITLE
Add Carthage support

### PR DESCRIPTION
**Pull request by rjsamson**
This pull request enables [Carthage](https://github.com/Carthage/Carthage) support by creating a shared scheme. It also updates the README to reflect Carthage support and adds a Carthage compatible badge to the README. If this PR is accepted a new tagged release needs to be added before Carthage can be used to build the framework.

### CODE REVIEW

**Comment by rjsamson** [comment]
@ortuman did you have a chance to see this yet?

**Comment by lexrus** [comment]
+1
Please merge.

**Comment by rjsamson** [comment]
Just pinging @ortuman again - is there any particular reason why this isn't getting merged?

**Comment by PaulWoodIII** [comment]
+1 @ortuman

**Comment by cferrios** [comment]
+1 @ortuman

**Comment by rjsamson** [comment]
@ortuman this has been hanging out there for a while now - any particular reason not to support Carthage? It's a pretty trivial change.

**Comment by ortuman** [comment]
Done! Sorry for the delay. Last months had been madness. Thank you!!!

**Pull request merged**
